name: Build Godot Project

on:
  push: {}
  pull_request: {}

env:
    GODOT_VERSION: 4.3.0

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Initial Godot Import
          shell: bash
          run: |
            godot4.3 --headless --import || exit 0
  
        - name: Setup Godot
          uses: chickensoft-games/setup-godot@v2
          with:
            version: ${{ env.GODOT_VERSION }}
            use-dotnet: false
            include-templates: true

        - name: Export Godot Project
          shell: bash
          run: >
            godot
            --headless
            ${{ matrix.export-args }}
            --export-${{ matrix.export-type }} "${{ matrix.export-preset }}"

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.archive }}-Artifacts
            path: |
              ${{ matrix.export-folder }}/*.*
              !**/.gitignore
