name: Build Godot Project

on:
  push: {}
  pull_request: {}

env:
    GODOT_VERSION: 4.3.0

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build
          id: build
          uses: manleydev/build-godot-action@v1.5.0
          with:
            name: example
            preset: ${{ matrix.platform }}
            debugMode: "true"

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.archive }}-Artifacts
            path: |
              ${{ matrix.export-folder }}/*.*
              !**/.gitignore
